name: Auto Assign PR Reviewers
on:
  pull_request:
    types: [opened, reopened]
permissions:
  pull-requests: write
jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          addReviewers: author
